KULeuven-MICAS/snax-mlir

.github/workflows/build-docker.yml
README.md
container/Dockerfile

Courtesy of @nazavode
This dockerfile does the following:
Stage 1:  Inside the snitch_cluster container:
1) Download the latest  `https://github.com/kuleuven-micas/snitch_cluster.git` and build it with verilator.
2) compile `spike-dasm` and install
3) compile `snitch runtime`
4) download snitch-specifc versions of clang/llvm/lld
5) download and compile python 3.11
Stage 2: Inside the `ubuntu 18.04` container:
1) copy-paste all binaries built in the previous stage
2) install python's ubuntu dependencies
3) install git
4) install a pre-built mlir (version 16.0.6), available as `mlir-opt-16` inside the container, optimized build, without assertions
5) install make
I'm currently/temporarily providing a public build of this dockerfile here for you to try out:
```
docker pull …
```

Add Dockerfile

---

.github/workflows/build-run-kernel.yml
README.md
kernels/simple_mult/Makefile
kernels/simple_mult/baseline.c
kernels/simple_mult/gendata.py
kernels/simple_mult/linalg.mlir
kernels/simple_mult/main.c
runtime/Makefile.rules
runtime/tollvm12.py

Makefiles, main.c, baseline.c and tollvm12.py script are courtesy of @nazavode :heart: 
Other files are made by me.
Initial example of a compilation flow (to CPU) to run stuff (a kernel that could run on HWPE-mac engine) on cpu 0 of a snitch_cluster.
This PR is ready for review in my opinion, but I'm waiting for a few things:
* A PR from Joren that installs stardew (I need to add numpy to a requirements file for gendata.py)
* A PR from Ryan that  changes the default snax config hjson (we can merge before!)
After Joren's PR I can add a CI job that runs all kernels in CI and checks for errors

Add simple HWPE integer multiplication kernel

---

README.md

This adds some instructions to perform dissasembly, tracing and should make it easier for newcomers to get started.
In terms of tutorial this is not yet a full blown tutorial ( I think it is too early for that ).
A proper tutorial would have examples etc.

docs: Add tracing, disassembly instructions, harmonize docker image naming

---

.gitignore

Expand the .gitignore file to exclude common build files and python thingies (env, pycache, ...)

expand .gitignore

---

.github/workflows/build-run-kernel.yml
.github/workflows/lit-tests.yml
.gitignore
kernels/simple_mult/main.c
runtime/Makefile.rules
runtime/tomlir16.py
runtime/tomlir18.py

This pull request implements an end-to-end flow from mlir to simulation on a snitch cluster. The steps taken look like this:
Preprocess the input mlir to with generic printing and local scope
`input.mlir ->  input.preproc.mlir`
Translate MLIR 16 to MLIR18 with a python script
`input.preproc.mlir -> input.preproc18.mlir`
Apply the custom `snax-opt` compiler. This includes passes to lower the linalg generics to external function calls which drive the accelerator
`input.preproc18.mlir -> input.snax-opt18.mlir`
Translate back to MLIR 16
`input.snax-opt18.mlir -> input.snax-opt.mlir`
Now use the existing MLIR workflow to lower and translate the remaining MLIR to LLVM, compile and run

end-to-end workflow

---

kernels/simple_mult/baseline.c
kernels/simple_mult/main.c
runtime/Makefile.rules
runtime/include/memref.h

This PR steps away from bare-ptr-calling-conv in mlir and uses mlir's C wrappers instead.
This means that we can represent more shapes (even dynamic ones! - but not unranked ones :( ).
We can also only represent strided memrefs, not just any memref.
Note that this applies the new wrappers to both the calling functions and the called functions of mlir.
I'm expecting a slight performance degradation from this update, this might mean that we should look into lto with LLD?

Add memref calling convention

---

container/Dockerfile
requirements.txt

Apperently, numpy was only installed in the container because it was a dependency of torch-mlir.
This pull request adds numpy to the requirements, and also installs the requirements of this repository in the container build

add numpy to requirements

---

container/Dockerfile
requirements.txt

Filecheck and lit are already moved, so we can just drop them.

Move dependences to requirements.txt

---

.github/workflows/build-docker.yml
container/Dockerfile
requirements.txt

Filecheck and lit are already moved, so we can just drop them.

Move dependences to requirements.txt (#40)

---

compiler/transforms/set_memory_space.py
kernels/simple_mult/linalg.mlir
tests/filecheck/transforms/set-memory-space.mlir

This PR adds dynamic shape support for the pass `set-memory-spaces`. 
If the pass realizes a memory cast on dynamically shaped memrefs, the dynamic allocations are now correctly handled.
The kernel `simple_mult` is adapted to use dynamic shapes.

add dynamic alloc support

---

kernels/simple_copy/main.c
runtime/include/snax_rt.h

This PR fixes the `simple_copy` kernel for LLVM17.
Apperantly, the turbo-charged blazingly quick llvm17 code is so fast that the kernel starts checking the result before the DMA transfer is finished. For this reason, i suggest simply inserting a dma wait by default in the runtime. This can later be optimized such that we only wait for DMA results when we need them, but no system like that is in place right now.

fix simple_copy kernel

---

.github/workflows/build-run-kernel.yml
.github/workflows/lit-tests.yml
.github/workflows/python-tests.yml
README.md
compiler/transforms/set_memory_space.py

This PR aims to resolve #52, partly.
When bumping xdsl, the new version is only installed in the docker build test, but other python tests still run on the docker build from the main branch.
I included rules to first update the python requirements from requirements.txt for python tests, such that the correct version of xdsl is used.
This resolves the problem when bumping modules defined in requirements.txt. However, this does not solve the problem for modules only defined in the Dockerfile (such as the snax-cluster).
Additionaly, this also includes the bugfix of the changed IntAttr xdslproject/xdsl#1825

fix xdsl bug

---

compiler/parser/tsl_parser.py
tests/filecheck/dialects/tsl/tsl.mlir
tests/filecheck/lit.cfg

The TSL still had a reverse operation when parsing the strides and bounds, interpreting the innermost strides as the outermost ones. The filecheck tests did not catch this error because the XDSL roundtrip parses and prints the IR twice, putting the steps and bounds back in their correct order 😒 
Additionaly i also renamed some functions, to be more consistent with the naming of:
A `Stride` consists of a `step` and a `bound`

fix tsl parsing error

---

compiler/util/kernel_type.py
tests/util/test_kernel_type.py

This PR inits the kernel_type util
The Kernel Type is an enum, to classify different kernels of a linalg body. For now, the code can classify the following kernels:
- MUL
- MAC
- QMAC
however, extending for other types of kernels should be easy with the implemented structure.
These changes pave the way for linalg.generic matching.
The Enum has a lot of functions. The most important one is `get_kernel`, where we identify the kernel type based on linalg operation as input. All of the other functions are helper parser functions to perform this identification.

add kernel_type util

---

compiler/dialects/snax.py
tests/dialects/test_snax.py
tests/filecheck/dialects/snax/snax_ops.mlir
tests/filecheck/lit.cfg

This PR adds the reshuffle op.
This is meant to be an equivalent to how we use `memory_space_cast`, by casting a specific memref to another memref with a different layout. Note that this operation does not create a copy. The copies/actual transformation is realized by a following pass. How the reshuffling is performed can vary.

dialect: (snax) add reshuffle op

---

compiler/tools/snax_opt_main.py
compiler/transforms/set_memory_space.py
runtime/Makefile.rules
tests/filecheck/transforms/realize-memory-space-casts.mlir
tests/filecheck/transforms/set-memory-space.mlir

This PR splits up the set-memory-layout pass into two:
1. `set-memory-layout`: insert casts
2. `realize-memory-space-casts`
This is because we want to do stuff inbetween the two passes as well. 
For example, based on the layer to which an accelerator is dispatched, we can decide to which memory space it will be cast. After this, we decide on a given memory layout. After this, we can realize the memory space casts and reshuffling operations at once.

split up cast realization pass

---

compiler/ir/tsl/tiled_stride.py
compiler/ir/tsl/tiled_strided_layout.py
tests/ir/tsl/test_tiled_stride.py
tests/ir/tsl/test_tiled_strided_layout.py

This PR extends the tsl with some useful functions necessary for better transformation support.
The algorithm to transform layouts only works from tsl -> tsl.
For memrefs with no layout or a simple stridedlayoutattr, it would therefore be useful to create tsl representations
of these layouts to still be able to use the current transformation algorithm

Extend TSL classes

---

compiler/tools/snax_opt_main.py
compiler/transforms/set_memory_layout.py
tests/filecheck/transforms/set-memory-layout.mlir

This PR implements an initial pass for enforcing memory layouts when operations are disptached to certain accelerators. Currently, the implementation is very naive. It imposes a specific memory layout on the input and output of the linalg operation dispatched to snax_qgemm by inserting layout casting ops. In the future, the memory layout will be selected in a more intelligent, automatic way.

add memory layout pass

---

compiler/dialects/tsl.py
compiler/transforms/snax_copy_to_dma.py
kernels/transform_copy/Makefile
kernels/transform_copy/gendata.py
kernels/transform_copy/main.c
kernels/transform_copy/transform_copy.preprocfinal.mlir
kernels/transform_copy/transform_from_none.preprocfinal.mlir
kernels/transform_copy/transform_from_strided.preprocfinal.mlir
tests/filecheck/transforms/copy_to_dma.mlir

building on top of #79, this extends the snax-copy-to-dma pass to apply transformations from `tsl->tsl` to `nonetype->tsl`, `strided->tsl` and the other way around

Enable transformations from other layouts

---

.github/workflows/build-run-mlperf-tiny.yml
runtime/Makefile.rules

This PR adds flows that don't use any of the middle-end optimizations that we have made with xDSL.
You can now make the binaries, by calling:
```sh
make network_name.no-snax-opt.o
```
Solves #22

Add vanilla MLIR flows

---

.github/workflows/build-run-mlperf-tiny.yml
compiler/transforms/clear_memory_space.py
compiler/transforms/linalg_to_library_call.py
compiler/transforms/set_memory_space.py
runtime/Makefile.rules
tests/filecheck/transforms/linalg-to-library-call.mlir
tests/filecheck/transforms/set-memory-space.mlir

This clears the pipeline to go directly to a RISC-V object file, yet networks are not actually run yet.
* A small error was found in the emission of `memref.get_global`s , where `name` and not `name_` was passed to the newly created op.
* There was a function call mismatch, where emitted function calls and declarations were incompatible with the shapes of various different calls. This was solved by declaring the functions with dynamic shapes and inserting casts to dynamic shapes.
* A pass (in the makefile) was integrated (with sed) to deal with minf, maxf to minimumf, maximumf conversion
* The `--clear-memory-space` pass was altered to only remove TSL layout attributes, other layout info is untouched.
* `--lower-affine` and `--expand-strided-metadata` passes were added to lower to LLVM …

mlperf tiny: Lower to object file

---

compiler/dialects/tsl.py
compiler/transforms/memref_to_snax.py
tests/filecheck/transforms/copy_to_dma.mlir
tests/filecheck/transforms/memref_to_snax.mlir

This PR adds dynamic support to the memref-to-snax pass. Now memref.allocs with dynamic shapes can also be lowered to snax dialect
The changes necessary are quite minimal, but there are some large diffs due to some refactoring, see my comments

add dynamic support to memref-to-snax pass

---

compiler/dialects/snax.py
compiler/transforms/memref_to_snax.py
tests/filecheck/dialects/snax/snax_invalid.mlir
tests/filecheck/dialects/snax/snax_ops.mlir
tests/filecheck/transforms/memref_to_snax.mlir

This PR adds an alignment property to the `snax.alloc` op
This is important to us if we want to align a memref with a specific memory bank

snax.alloc: add alignment property

---

compiler/transforms/memref_to_snax.py

To fix the errors in mlperf tiny benchmarks from #90

limit lowering to snax.alloc to memory space L1

---

compiler/dialects/snax.py
compiler/transforms/memref_to_snax.py
tests/dialects/test_snax.py
tests/filecheck/dialects/snax/snax_ops.mlir
tests/filecheck/transforms/memref_to_snax.mlir

For futher lowering the `snax.alloc` operation, we need the shape information to populate the llvm memref descriptor. The shape operands are already inserted in the ir, this PR just includes them as actual operands of the `snax.alloc` op.

add shape operands to snax alloc op

---

compiler/transforms/memref_to_snax.py
compiler/transforms/snax_to_func.py
kernels/simple_mult/main.c
runtime/Makefile.rules
runtime/include/snax_rt.h
tests/filecheck/transforms/snax_to_func.mlir

The PR implements a lowering which replaces `snax.alloc` calls with the relevant function call and populates the llvm memref descriptor accordingly.
Note: although there are no changes to the `alloc` kernel (and other kernels using a `memref.alloc`), this kernel now uses this updated flow, and keeps operating correctly!

compiler: snax.alloc to func lowering

---

compiler/dialects/acc.py
compiler/tools/snax_opt_main.py
compiler/transforms/acc_cse.py
tests/dialects/test_acc.py
tests/filecheck/dialects/acc/ops.mlir
tests/filecheck/transforms/acc-cse.mlir

`acc` dialect: (snax) accelerator setup and dispatch code, used to represent setup, launching and waiting for accelerator calls.
`acc-cse` pass: elide redundant setup operations from IR.

dialects: (acc) Add acc dialect and acc-cse pass to simplify setups

---

compiler/dialects/acc.py
compiler/inference/trace_acc_state.py
compiler/tools/snax_opt_main.py
compiler/transforms/acc_cse.py
compiler/transforms/convert_linalg_to_acc.py
runtime/Makefile.rules
tests/filecheck/dialects/acc/ops.mlir
tests/filecheck/transforms/acc-cse.mlir
tests/filecheck/transforms/convert-linalg-to-acc.mlir
tests/inference/test_acc_state_tracing.py

This PR contains:
- Rename `acc` to `acc2`, as `acc` is already used for the openACC dialect in MLIR
- A new `convert-linalg-to-acc` pass:
- That converts linalg annotated with `library_call = "snax_hwpe_mult"` to acc2 dialect ops
- That then connects the `!acc2.state` ssa values through the IR such that they conform to the control flow (currently handles `scf.if` but not `scf.for`)
- Improvements to the `acc-cse` pass that is now able to infer states through `scf.if` ops. 
- A test that depends on `mlir-opt` passes, we marked it `XFAIL` for now until we can update to a commit of xDSL that contains xdslproject/xdsl#2293

Lower linalg to acc2 dialect

---

compiler/transforms/snax_to_func.py
kernels/alloc/func.mlir
kernels/alloc/main.c
runtime/include/snax_rt.h
tests/filecheck/transforms/snax_to_func.mlir

This PR adds support for aligned allocation.
This can be used for aligning a certain memref to a bank in memory to avoid bank collisions

add aligned allocation support

---

compiler/dialects/acc.py
compiler/tools/snax_opt_main.py
compiler/transforms/acc_cse.py
compiler/transforms/acc_dedup.py
tests/filecheck/dialects/acc/ops.mlir
tests/filecheck/transforms/acc-cse.mlir
tests/filecheck/transforms/convert-linalg-to-acc.mlir

Stacked on top of #103 
This PR:
- Renames `acc-cse` to `acc-dedup` to better reflect what it's doing
- Adds a rewrite to hoist setup calls into `scf.if` operations

Improve acc dialect optimizations

---

compiler/dialects/acc.py
compiler/tools/snax_opt_main.py
compiler/transforms/convert_acc_to_csr.py
compiler/transforms/convert_linalg_to_acc.py
tests/filecheck/dialects/acc/ops.mlir
tests/filecheck/transforms/acc-cse.mlir
tests/filecheck/transforms/convert-acc-to-csr.mlir
tests/filecheck/transforms/convert-linalg-to-acc.mlir

This PR introduces a new pass `convert-acc-to-csr` that converts `acc` dialect ops to llvm inline assembly setting CSR register values.
It also adds a `acc2.accelerator` operation that defines acclerator specific addresses and such, which is used by the lowering.

Add backend for acc2 dialect

---

compiler/accelerators/accelerator.py
compiler/accelerators/snax.py
compiler/accelerators/snax_hwpe_mult.py
compiler/transforms/convert_acc_to_csr.py
compiler/transforms/convert_linalg_to_acc.py

This PR adds an abstract base class that implements an interface for converting to and from acc2 dialect.
The idea is that people adding new accelerators mainly add stuff in a subclass of `AcceleratorInterface` and that then they should be good to go. This should also enable people to add non-SNAX accelerators, or for us to more quickly adapt to general changes in SNAX architecture.
Going to acc2 dialect:
* `generate_setup_vals`: To insert the right values (coming from anywhere in the IR) to the SetupOp, I expect this part of the interface will have to be reworked soon.
* `generate_acc_op`: To create instances of an AcceleratoOp, the accelerator_op itself might need to be a bit more flexible in what types of barriers it supports etc. This might have repercussions on the lowering of …

acc2: Refactor AcceleratorInterface

---

compiler/transforms/memref_to_snax.py
tests/filecheck/transforms/memref_to_snax.mlir

The offset was not considered when calculating the size to allocate for TSL layouts. This PR fixes that

use offset in memref-to-snax

---

compiler/accelerators/registry.py
compiler/transforms/convert_acc_to_csr.py
tests/filecheck/transforms/convert-linalg-to-acc.mlir

This PR solves the problem that if there are multiple accelerators in the IR they should be lowered in a different way.
It adds a "registry" = a dict that maps symbol names to the Accelerator interface introduced in #114 .
That way we can query the right lowering through the `accelerator.op`'s symbol at runtime.
Right now it's very simple, but this can be made more complex in the future if necessary.
Note that this requires the IR to be annotated with the acc.AcceleratorOp, otherwise the right passes can not be queried. Before they were hardcoded :) so it wasn't necessary to put them there.
Note that the lowerings from linalg are still hardcoded. This is work for the next PR.

acc2: Add an accelerator registry for lowering transforms

---

compiler/accelerators/accelerator.py
compiler/accelerators/snax.py
compiler/accelerators/snax_hwpe_mult.py
compiler/dialects/acc.py
compiler/transforms/convert_linalg_to_acc.py
tests/filecheck/dialects/acc/ops.mlir
tests/filecheck/transforms/acc-cse.mlir
tests/filecheck/transforms/convert-acc-to-csr.mlir
tests/filecheck/transforms/convert-linalg-to-acc.mlir
tests/filecheck/transforms/insert-acc-op.mlir

This PR adds the possibility of adding SSAValues and fields to the acc2.LaunchOp.
This is to fix the case where some accelerators also perform some setup implicit on each launch.
The nice thing is that encoding it like this immediatly makes it impossible to deduplicate those calls (that never have to be deduplicated in the first place) but still allows us to perform some configuration inside the launching of accelerators.
This is necessary to be pushed first to allow for #118 to be added
This also replaces the generate_setup_vals with an even more opaque mechanism in the interface to generate the entire sequence of setup, launch and await ops instead, which is required in this case, since some setup operations are not tied to just the setup op anymore

acc2: Add values to launch field

---

compiler/accelerators/rocc.py
tests/filecheck/transforms/rocc-dedup.mlir

Note: stacked PR
This adds support to emit RoCC instructions for setup values that were previously deduplicated.
In certain cases this means that you need to trace back what the original rs1 was associated to an rs2 or vice versa.
Note that this changes a previously implemented test to not be failing anymore.

acc2: Add deduplication recovery support for gemmini 

---

kernels/mlperf_tiny_ad01/Makefile
kernels/mlperf_tiny_ic/Makefile
kernels/mlperf_tiny_kws/Makefile
kernels/mlperf_tiny_vww/Makefile

this pr sets up a proper clean statement in the makefiles for the mlperf tiny benchmarks

make: Fix clean for mlperf tiny

---

compiler/accelerators/accelerator.py

Seems like the proper way to define abstract base classes is to throw errors if they are ever used instead of just passing.

acc2: Add noimplemented to ABC

---

pyproject.toml

because anton is a modern man with a modern terminal
is 120 enough? 300 like you have in xDSL seems outrageous

ruff: increase line length

---

compiler/dialects/acc.py
tests/filecheck/dialects/acc/ops.mlir
tests/filecheck/dialects/snax/snax_ops.mlir
tests/filecheck/lit.cfg
tests/filecheck/transforms/acc-cse.mlir
tests/filecheck/transforms/accfg-trace-states.mlir
tests/filecheck/transforms/convert-linalg-to-acc.mlir

Broke this out of #129 because it's already a chonker
This makes it easier to understand setup ops (e.g. the input state is no longer mixed with the values, and the "key = value" pairs are closer together.

Add custom syntax for acc.setup

---

runtime/include/snax_rt.h

There was a missing barrier in one of the runtime routines, resulting in fun-to-debug erronous behaviour.

Add DMA barrier hotfix

---

compiler/ir/tsl/tiled_strided_layout.py
compiler/transforms/snax_copy_to_dma.py
tests/filecheck/transforms/copy_to_dma.mlir

This PR implements support for copying strided memrefs, including those with transformations. This works by creating a TSL representation of the stridedlayoutattr and then applying the existing algorithm on the tsl representations.

support strided copies

---

compiler/transforms/snax_copy_to_dma.py
kernels/transform_copy/transform_from_strided.preprocfinal.mlir
tests/filecheck/transforms/copy_to_dma.mlir

Apply element strides for strided attribute when forming tsl from `StridedLayoutAttr`, as this accounts for element width, while tsl does not

fix strided transform copy bug

---

compiler/inference/helpers.py
compiler/inference/scoped_setups.py
compiler/transforms/accfg_config_overlap.py
compiler/transforms/accfg_dedup.py
compiler/transforms/convert_linalg_to_accfg.py
flake.lock
flake.nix
tests/filecheck/transforms/accfg-config-overlap.mlir
tests/filecheck/transforms/accfg-trace-states.mlir

This PR adds ScopedSetupWithInputs and moves a bunch of helpers out of the rewrites and into the `inference` module.
ScopedSetupWithInputs represents a setup op together with operations that calculate it's inputs. These operations must be pure, and be contained within a block (usually the block at which the operation is located).
This helper class is needed for stacked PR 3/3, and will also be helpful to simplify some other rewrites I'm sure,

Add ScopedSetupWithInputs (stacked 2/3)

---

kernels/streamer_alu/gendata.py
kernels/streamer_alu/main.c
kernels/streamer_alu/streamer_add.mlir
runtime/include/memref.h

I've corrected the pointers to not include the sign extension anymore and to also not use magic pointer arithmetic (to avoid future confusion)

Adapt sizes to new 64 bit pointers in streamer alu

---

compiler/dialects/snax.py
compiler/tools/snax_opt_main.py
compiler/transforms/snax_lower_mcycle.py
tests/filecheck/dialects/snax/snax_ops.mlir
tests/filecheck/transforms/snax_lower_mcycle.mlir

This PR adds an operation that adds a utility mcycle operation to the snax dialect.
This is useful to split up traces in multiple sections

Add snax.mcycle op

---

compiler/dialects/accfg.py
compiler/inference/helpers.py
compiler/transforms/convert_linalg_to_accfg.py
tests/filecheck/dialects/acc/ops.mlir

The idea is that:
- function calls (`func.call` and `llvm.call`) are pessimistically assumed to effect the accelerator
- any other op does not effect the accelerator if ops in their body don't 
- Both of these assumptions can be overwritten by setting the `accfg_effects` attribute to `#accfg.effects<none>` or `#accfg.effects<full>`.

dialects: (accfg) Add accfg.effects attribute

---

compiler/ir/tsl/tiled_strided_layout.py
compiler/transforms/snax_copy_to_dma.py
tests/filecheck/transforms/copy_to_dma.mlir

When looking for a largest contiguous block, we were too conservative when bumping into dynamic dimensions. This results in a copy from a `memref<?xi32, strided[1]>` to be copied in chunks of single elements, even though the data is still contiguous.
This PR should hopefully fix this.

support dynamic lcbs

---

compiler/dialects/snax_stream.py
compiler/tools/snax_opt_main.py
tests/filecheck/dialects/snax_stream/snax_stream_ops.mlir

This PR adds the snax_stream dialect.
In many ways, it is a copy of the snitch_stream dialect, with the following changes to adapt it to SNAX Streamers:
- operate on indeces instead of riscv registers
- use a stride pattern with upper bounds, temporal strides, spatial strides

add snax-stream dialect

---

compiler/accelerators/snax.py
compiler/accelerators/streamers/__init__.py
compiler/accelerators/streamers/streamers.py
compiler/dialects/snax.py
compiler/dialects/snax_stream.py
tests/filecheck/dialects/snax/snax_ops.mlir
tests/filecheck/dialects/snax_stream/snax_stream_invalid.mlir
tests/filecheck/dialects/snax_stream/snax_stream_ops.mlir

note: stacked on #175 
This PR includes the following:
- A representation of the Streamers in `accelerators/streamers/streamer.py`
- An attribute which holds as data a StreamerConfiguration: `StreamerConfigurationAttr`
- This attribute can be passed along with an `accfg.AcceleratorOp`.
- The `snax_stream.streaming_region_op` now comes with a verifier that does the following:
- The region must be linked to an accelerator
- The accelerator must implement a streamer interface, through the streamer configuration attribute
- All of the dimensions of the stride pattern must mach the streamer interface implementation
- It also includes a `SNAXStreamer` base class, which can be inherited by other accelerators, this class will then handle anything streamer-related automatically, based on the …

Add snax streamer interface

---

compiler/dialects/tsl.py
runtime/Makefile.rules

if everything is dynamic, default tsl striding to the most right stride (row-major-like)

fix tsl dynamic

---

compiler/accelerators/snax.py
compiler/accelerators/snax_alu.py
compiler/dialects/snax_stream.py
compiler/tools/snax_opt_main.py
compiler/transforms/stream_snaxify.py
kernels/streamer_alu/Makefile
kernels/streamer_alu/streamer_add_stream.preprocfinal.mlir
tests/filecheck/dialects/snax_stream/snax_stream_invalid.mlir
tests/filecheck/dialects/snax_stream/snax_stream_ops.mlir
tests/filecheck/transforms/stream-snaxify.mlir

This pass converts a `memref.streaming_region_op` into a `snax_stream.streaming_region_op`. 
This is somewhat similar to the pass `convert_memref_stream_to_snitch_stream` in xdsl. I am refactoring some stuff over there to share some more code.
It also updates the lowering for the `snax_alu` accelerator to start from `memref_stream`.

add stream-snaxify pass

---

compiler/accelerators/snax.py

The order of programming is first streamer, then dim. This was implemented the other way around (wrong)

dialects: (accfg) fix streamer lowering

---

compiler/util/kernel_type.py
tests/util/test_kernel_type.py

The snax-alu accelerator implements elementwise addition. To be able to dispatch and detect this, the ADD kernel type is added to the kernel utilities.
This also fixes some weird things I found in the test.
Such as `arith.Constant(IndexType(), 1)`, which is a completely invalid call of the constructor, but does not throw an error as the op is never verified/inserted in ir/ value is requested :)

util: (kernel_type) add Kerneltype.ADD kernel

---

compiler/tools/snax_opt_main.py
compiler/transforms/guarded_linalg_to_memref_stream.py
tests/filecheck/transforms/guarded-linalg-to-memref-stream.mlir

Upstream xdsl converts all linalg.generic calls to memref.generic calls. We don't always want this. This pass adds an extra guard to only convert linalg.generic which are dispatched to an accelerator, appended with the _stream suffix. It then removes the suffix after the conversion is done.

transform: (guarded-linalg-to-memref-stream) init pass

---

compiler/util/canonicalize_affine.py
tests/util/test_canonicalize_affine.py

The algorithms used in the stream transform passes try to compare different affine maps. To be able to compare them, this utility function tries to implement some canonicalization. It is quite barebones, but it suffices for now. Future work is to implement the full flattening of affine maps in upstream MLIR in xdsl so we can use that, but this is quite some work.

util: add canonicalize_affine_map

---

compiler/transforms/dispatch_kernels.py
tests/filecheck/transforms/dispatch_kernels.mlir

This, so the dispatching now dispatches elementwise additions to the snax alu. 
Additionally, this pass decides if the kernel can be dispatched using the stream programming model. 
If this is the case the `_stream` suffix is appended to the library call. This is a temporary workaround such that the `convert-linalg-to-memref-stream` only converts the generic kernels dispatched to a streamer accelerator.
As this only supports static sizes for now, dynamic sizes still use the old programming model.

transform: (dispatch_kernels) add SnaxALU Rules

---

compiler/dialects/tsl.py
compiler/ir/tsl/README.md
tests/dialects/test_tsl.py

To be able to stream-snaxify, we must have an affine mapping from data to memory. This implements this for TSL layouts, such that these are supported as well as NoneAttr and StridedLayoutAttr.
One caveat is that the definition of `get_affine` is to return the element offset. TSL returns the byte offset. In hindsight, I will probably refactor tsl layouts to use element offset instead at a later stage, once the dust settles.
For a TSL with bounds
$$
\left[b_{0,M}, ..., b_{0,1}, b_{0, 0}\right], \left[b_{1,K}, ..., b_{1,1}, b_{1, 0}\right], ...
$$
and tiled strides for every dim $d$:
$$
\left[b_{d,M}, ..., b_{d,1}, b_{d, 0}\right] \rightarrow \left(s_{d,M}, ..., s_{d,1}, s_{d, 0}\right)
$$
The affine map is given by:
$$(i_0, i_1, ..., i_n) \rightarrow
\sum_{n=0}^{N-1}\sum_{m=0}^{M-1} s_{n,m} …

dialects: (tsl) implement get_affine_map

---

compiler/transforms/stream_snaxify.py
tests/filecheck/transforms/stream-snaxify.mlir

When transforming the `memref_stream.streaming_region_op` to `snax_stream`, we must add an accelerator attribute to the `snax_stream` op, which is not included in `memref_stream`. For this, we just look at the generic op in the body and see if it has a library call assigned to it

transform: (stream-snaxify) accelerator attribute hoisting

---

compiler/tools/snax_opt_main.py
compiler/transforms/schedule_memref_linalg.py
tests/filecheck/transforms/schedule-memref-linalg.mlir

This PR adds the first version of the schedule-memref-linalg pass.
This pass matches and transforms an operation on an accelerator template.
At this stage, this is quite barebones, and only functional for easy examples (elementwise operation on elementwise snax-alu accelerator/ gemm operation on gemm accelerator).
This document is an effort to explain its workings at the current stage.
[schedule-memref-linalg.pdf](https://github.com/user-attachments/files/16744943/schedule-memref-linalg.pdf)
Many improvements to this algorithm will come very shortly :)

transform: schedule-memref-linalg pass

---

compiler/transforms/stream_snaxify.py
tests/filecheck/transforms/stream-snaxify.mlir

This allows _any_ layout that has an affine map defined to be used by the stream lowering.
There are also some fixes to include more dimensions for the gemm, these are maybe somewhat unethical.

 transform: (stream_snaxify) extend to all data layouts and more dimensions

---

compiler/ir/tsl/tiled_strided_layout.py
compiler/transforms/set_memory_layout.py
tests/filecheck/transforms/set-memory-layout.mlir

The tsl's were given dynamic strides and bounds, even for static problem sizes.
The assumption that everything downstream easily handles dynamic layouts is not always as convenient :)
This makes sure the layout attribute is exactly as statically determined as the memref it is assigned to.

transforms: (set-memory-layout) make tsls more static

---

.github/workflows/build-run-kernel.yml
compiler/accelerators/gemmini.py
compiler/accelerators/rocc.py
kernels/gemmini/Makefile
kernels/gemmini/tiled_matmul.transform.mlir
runtime/Makefile.rules
tests/filecheck/transforms/rocc-dedup.mlir

This PR implements the following:
* A conversion from linalg generic to Gemmini's weight-stationary kernel
* A "temporary fix" to allow deduplicated RoCC code to be converted to CSRs.
Right now there is no way to create pairs if one of the pairs is deduplicated. 
The `create_pairs` function will try to catch the previous state to create a pair again, but this is not possible if only half of the pair is set in said previous state.
As a first fix, this test assumes all settings are set in pairs, and a constant default is appended to the very first setup op in the state chain (the one without an in_state). This makes sure that a default value is set to rs1 if rs2 is set - but not rs1 - and vice versa.  A more thorough fix for this actually might reset all values at first? Any suggestions …

Add gemmini Loop WS kernel support through ACCFG

---

compiler/transforms/reuse_memref_allocs.py

Fix an issue where when both static_sizes and dynamic sizes are used together in a subview, their sizes can' be indexed to correctly

Fix Reuse memref Allocs Issue

---

compiler/transforms/convert_linalg_to_accfg.py
tests/filecheck/transforms/accfg-trace-states.mlir

if there is an op that's not specifically handled, we just recurse in the body of that op, without carrying state in or out

Make state tracing work in scf.parallel and such

---

compiler/accelerators/snax.py
compiler/accelerators/snax_alu.py

This was due for merging in #224 2 months ago, where an unstable barrier was detected during benchmarking.
This should solve that issue, but adds yet another barrier :(
It's a cherry-picked version of a7e8eb70e6a05c21ad21b38ef866a463357afc0e

Add snax-alu barrier fix

---

compiler/tools/snax_opt_main.py
compiler/transforms/test_add_mcycle_around_loop.py
tests/filecheck/transforms/test-add-mcycle-around-loop.mlir

This pass adds two snax-mcycle ops, one right before, and one right after all top-level scf for loops inside a function.
This pass is to be used for measurement purposes only.

Add test-add-mcycle-around-loop pass

---

compiler/accelerators/snax.py
compiler/accelerators/snax_alu.py
compiler/accelerators/snax_gemm.py
compiler/accelerators/streamers/streamers.py
compiler/dialects/snax.py
compiler/transforms/stream_snaxify.py
tests/filecheck/dialects/snax/snax_ops.mlir
tests/filecheck/dialects/snax_stream/snax_stream_invalid.mlir
tests/filecheck/dialects/snax_stream/snax_stream_ops.mlir

This PR extends the streamer configuration attributes so that each streamer dimension can have a flag assigned to it.
This allows us to express the irrelevance of certain dimensions or possible reuse within the accelerator, such that we can program the streamers correctly.
Additionally, this pr also deprecates and starts moving away from the global `spatial_dim` and `temporal_dim` functions. These are only valid when the temporal/spatial dim is equal for every operand, which is only the case for very simple examples.

accelerators: (snax streamers) add streamer flags

---

compiler/dialects/kernel.py
compiler/tools/snax_opt_main.py
tests/filecheck/dialects/kernel/ops.mlir

start migrating this logic from `util` and formalize them as ops.
Kernel ops can be used to match accelerator templates

add kernel dialect

---

compiler/dialects/kernel.py
compiler/tools/snax_opt_main.py
compiler/transforms/convert_tosa_to_kernel.py
tests/filecheck/dialects/kernel/ops.mlir
tests/filecheck/transforms/convert-tosa-to-kernel.mlir

This PR specifies the convert-tosa-to-kernel pass, useful for the new rescaling op. In linalg.generic format, this op is humongous and very inconvenient to try and parse, so this pass just allows for a lowering straight from tosa

add convert-tosa-to-kernel pass

---

compiler/dialects/test/debug.py
compiler/tools/snax_opt_main.py
compiler/transforms/test/debug_to_func.py
compiler/transforms/test/insert_debugs.py
kernels/streamer_alu/Makefile
kernels/streamer_alu/main.c
tests/filecheck/transforms/test/debug-to-func.mlir
tests/filecheck/transforms/test/insert-debugs.mlir

This PR adds some testing infrastructure to better inspect larger kernels such as neural networks.
It allows for the automatic insertion of debug statements before and after every linalg.generic kernel.
The debug statements are later transformed into function calls. 
The function definition can be provided by the user in the `main.c` file, where you can inspect the operands given to you by the debug statements.
Because this is not really core infrastructure, i put all the files in a `test/` subfolder

add debugging dialect and pass

---

compiler/transforms/convert_tosa_to_kernel.py
tests/filecheck/transforms/convert-tosa-to-kernel.mlir

The output type was not set correctly in the resulting linalg.generic. The outs of a linalg on tensors must have the correct type, as it uses the `DestinationStyleOpInterface`. This output type can be generated with a `tensor.empty` operation

transform: (convert-tosa-to-kernel) use correct output type

---

compiler/dialects/kernel.py
compiler/transforms/convert_tosa_to_kernel.py
tests/filecheck/dialects/kernel/ops.mlir

A weird bug in MLIR causes the properties of my unregistered dialect to be removed during the fold tensor cast pattern when applying canonicalization.
Running this through canonicalize shows the bug: https://gist.github.com/jorendumoulin/03b55e6b467914de74a010e60590acb8
For now, this turns the properties into attributes such that we are not bothered by this bug

dialects: (kernel) turn rescale properties into attributes

---

kernels/alloc/main.c
kernels/rescale/main.c
kernels/simple_copy/main.c
kernels/streamer_alu/main.c
kernels/streamer_matmul/main.c
kernels/tiled_add/main.c
kernels/transform_copy/main.c

Right now, the kernels return the number of errors in `main.c`. However, this seems to cause some kernels succeeding in CI even though they are wrong. For example, upon returning 256, CI will not fail.
Examples:
Succeeding test when returning 256: https://github.com/KULeuven-MICAS/snax-mlir/actions/runs/11012247027/job/30578039634
Failing test when returning 1: https://github.com/KULeuven-MICAS/snax-mlir/actions/runs/11012262776/job/30578088724
This PR just makes sure all kernels return 1 if an error occurs

kernels: return 1 on error

---

.github/workflows/run-benchmarks.yml
benchmarks/.gitignore
benchmarks/dense_matmul/Makefile
benchmarks/dense_matmul/genbenchmark.py
benchmarks/dense_matmul/gendata.py
benchmarks/dense_matmul/main.c

This adds a benchmark that measures peak performance of the gemm accelerator measuring from the time it is launched until it is finished.
It is configured to run the benchmark on every push to main, and uploads the output report to github artifacts, sneek peak available here:   https://github.com/KULeuven-MICAS/snax-mlir/actions/runs/11012799975

add dense matmul benchmark

---

.github/workflows/build-run-kernel.yml
.github/workflows/build-run-mlperf-tiny.yml
.github/workflows/lit-tests.yml
.github/workflows/python-tests.yml
compiler/accelerators/snax.py
compiler/accelerators/snax_alu.py
compiler/accelerators/snax_gemmx.py
compiler/accelerators/streamers/streamers.py
compiler/dialects/snax.py
compiler/transforms/stream_snaxify.py
tests/filecheck/dialects/snax/snax_ops.mlir
tests/filecheck/transforms/stream-snaxify.mlir

new streamers!
~~new bugs!~~
The most drastic change are in the spatial streamers, which are now all 1-dimensional. We need a better system to support code-generation for this, for which I have some ideas. In this PR, the spatial strides are hardcoded to [8]. Because in all of our tests the data accessed spatially is contiguous, this works, but is off course not a generally accepted solution.
I propose to do this in a follow up-PR to keep these changes nice and separated.
The changes in this PR mostly relate to the order in which the CSRs come, which has changed somewhat.
additionally, the `separate_bounds` flag is removed as it is now always separate
the readerwriter streamertype is removed as it is probably just a hardware concept that is better modeled as a separate reader and writer …

bump snax to v0.2.1

---

.github/workflows/gh-pages.yml
.gitignore
docs/benchmarks/index.md
docs/index.md

While most of the docs can remain on the `gh-pages` branch, the workflow needs to be in main to be able to be manually dispatched or through the cron schedule.
I also think it makes sense to keep the non-auto-generated docs in the main branch as well

init gh-pages workflows

---

.github/workflows/run-benchmarks.yml
benchmarks/dense_matmul/Makefile
benchmarks/dense_matmul/genbenchmark.py
compiler/transforms/set_memory_layout.py
tests/filecheck/transforms/set-memory-layout.mlir

add an argument to the pass to select between banked and cyclic layouts for gemm, to compare the results of both
update the dense benchmark to sweep over this new degree of freedom accordingly
this also defaults to cyclic layout, as it should be the better one

transforms: (set-memory-layout) add layout switch

---

compiler/accelerators/snax.py
compiler/transforms/stream_snaxify.py
util/snax_benchmark.py

If we generate a zero pattern with the streamers, we can use the optional channel mask to make sure we do not burden the tcdm with zero requests.

streamers: use channel mask for zero patterns

---

compiler/dialects/stream.py
compiler/tools/snax_opt_main.py
tests/filecheck/dialects/snax_stream/snax_stream_ops.mlir
tests/filecheck/dialects/stream/ops.mlir
tests/filecheck/transforms/stream-snaxify.mlir

There are certain things a bit annoying about the upstream `stream` + `memref_stream` dialect for our purposes, but I don't know what an optimal solution is, to experiment with this, this creates a more simplified, principled approach to the stream dialect to experiment what would be good for our purposes.
Changes made here:
- Inherent compatability with tensors for easier tiling/splitting/fusing
- Stream types have value semantics, e.g, no `stream.writeable` or `stream.readable`, just `stream.stream`.
- A stream.generic can **only** operate on streams, not on memrefs, and thus is always part of a streaming region
- no attempt to support imperfectly nested loops. to do this, add multiple stream.generics in a stream.streaming region
- stream.generic is kept as a subset of linalg.generic, …

add custom stream dialect

---

compiler/dialects/stream.py
compiler/tools/snax_opt_main.py
compiler/transforms/convert_linalg_to_stream.py
compiler/transforms/guarded_memref_streamify.py
tests/filecheck/transforms/convert-linalg-to-stream.mlir

With the simplifications of the custom stream dialect, this combines the `guarded-convert-linalg-to-stream`, `convert-linalg-to-stream`, `memref-streamify` into a single pass, with a significant loc reduction.
Awaits #274

add convert-linalg-to-stream pass

---

compiler/accelerators/snax_gemmx.py
compiler/tools/snax_opt_main.py
compiler/transforms/fuse_streaming_regions.py
tests/filecheck/transforms/fuse-streaming-regions.mlir

A pass to fuse multiple streaming regions if their bodies can be executed by the same accelerator.
This pass fuses single producer-consumer streaming regions if the consumer applies an elementwise function to the tensor, with the assumption that this will always be possible to fuse in the accelerator.
This works on tensor operands, so after this pass there should still be some form of bufferization.

add fuse-streaming-regions pass

---

compiler/tools/snax_opt_main.py
compiler/transforms/alloc_to_global.py
compiler/transforms/frontend/preprocess_mlperf_tiny.py
tests/filecheck/transforms/alloc-to-global.mlir

when doing bufferization in snax-opt itself, this one is quite useful. Now only used in mlperf, I also want to use it when using `stream-bufferize` and such

move alloc-to-global pass out of frontend

---

benchmarks/dense_matmul/Makefile
benchmarks/dense_matmul/genbenchmark.py
benchmarks/dense_matmul/gendata.py
benchmarks/dense_matmul/main.c
compiler/transforms/clear_memory_space.py
docs/benchmarks/index.md

From the updated docs:
> Testing peak utilization of the `snax-gemmx` accelerator, for different matrix sizes. Measures max performance without considering control overhead. This test generates a lot of results and plots to get deep insight into the performance of the accelerator combined with the TCDM interconnect and data layout strategies.
> 
> The following operations are compared:
> 
> - matmul (D = AxB)
> - gemm (D = AxB)
> 
> The following layout strategies are compared:
> 
> - cyclic
> - banked
> 
> The following sizes are run:
> 
> - every combination of (32, 48, 64)
> - some common sizes for neural networks
> 
This PR adds the gemm to this benchmark (previously only matmul)

add add-c to dense matmul kernel

---

.github/workflows/build-run-kernel.yml
kernels/alloc/main.c

There was a check for alignment to 256 bytes, but 64 bytes is sufficient.
Also add the kernel to ci
Resolves #260

fix alloc kernel

---

benchmarks/dense_matmul/genbenchmark.py
tests/benchmark/test_snax_benchmark.py
util/snax_benchmark.py
util/tracing/snax_event_generator.py
util/tracing/state.py
util/tracing/trace_to_perfetto.py

Adds SNAX specific event tracer to the trace_to_perfetto utilty:
The following three events are discerned to produce those traces:
* a "pre-launch" event, that:
- starts at the first CSR write to a config register
- ends after all launch fields have been written to
- records the number of setup instructions executed
* a "launched but not waiting" event, that:
- starts immediately after the "pre-launch" event
- ends on the second "write 0 to launch addr"
* a "waiting" event, that:
- starts on the first read from the barrier address
- ends when that read return 1
This should be general enough to support any SNAX accelerator, although I (@JosseVanDelm) am not entirely sure how to verify that in CI.
The utility was already useable standalone, but this patch makes it more difficult to specify …

Add SNAX specific events to the tracing script

---

runtime/Makefile.rules

This PR makes some changes to the `Makefile.rules` to allow for the pixi migration.
Other changes that are required (that would break things for now, so not included yet):
- inclusion of the /opt directory from the docker container
- `--test-linalg-transform-patterns="test-generalize-pad-tensor"` is renamed to `--linalg-detensorize="test-decompose-pad-tensor"`, the current mlir version in the docker is not exactly the same as the one in pixi

make Makefile.rules changes for pixi migration

---

compiler/ir/autoflow/__init__.py
compiler/ir/autoflow/affine_transform.py
tests/ir/autoflow/test_affine_transform.py

An AffineTransform helper, similar to the implementation in MLIR/xDSL.
However, the representation is handled by a matrix A and B instead of the AffineExpr tree, which should make things much easier. I plan to use this class inside the `compiler/ir/stream/access_pattern.py` utility classes.
This also gets rid of the canonicalization problem for affine transforms.

add affine transform util

---

compiler/ir/autoflow/affine_transform.py
tests/ir/autoflow/test_affine_transform.py

to keep interoperability with xdsl afinemaps, and to enable a more gradual migration to affinetransforms, include the constructors `from_affine_map` and `to_affine_map`

affine transform util: add interoperability with AffineMaps

---

compiler/ir/autoflow/affine_transform.py
compiler/ir/stream/access_pattern.py
compiler/transforms/convert_stream_to_snax_stream.py
tests/ir/stream/test_access_pattern.py

The SchedulePattern and AccessPattern things that were based on `AffineMaps` are now migrated to use `AffineTransforms`. This already simplifies things a lot
stacked on #324

AccessPattern utils: change to AffineTransform representations

---

compiler/accelerators/snax.py
compiler/accelerators/snax_alu.py
compiler/accelerators/snax_gemm.py
compiler/accelerators/snax_gemmx.py
compiler/dialects/stream.py
compiler/transforms/convert_stream_to_snax_stream.py

stacked on #331 
With the addition of the schedule op, this PR splits the `convert_stream_to_snax_stream` (which converts operation -> access pattern) into two separate passes (scheduler: operation -> schedule), (layout resolution: schedule -> access pattern).
The schedule representation is nice to have to run other passes on before doing layout resolution, such as selecting a layout.

split convert_stream_to_snax_stream in scheduler and layout resolution

---

compiler/dialects/stream.py
compiler/transforms/convert_stream_to_snax_stream.py
tests/filecheck/transforms/convert-stream-to-snax-stream.mlir

situation before this pr:
```
stream.streaming_region
--> autoflow-scheduler-pattern
stream.schedule_op
--> layout_resolution-pattern
snax_stream.streaming_region
```
The layout resolution includes a lot of gemmx specific hacks entagled between the logic of layout resolution, which is not nice. To keep everything clear this should be separated somewhat. This also makes it fit the mathematical model behind the passes more cleanly.
Therefore this pr splits it up into:
```
stream.streaming_region
--> autoflow-scheduler-pattern
stream.schedule_op
--> layout_resolution-pattern
stream.access_pattern_op
--> convert_stream_to_snax_stream-pattern
snax_stream.streaming_region
```
This PR doesn't change any logic, just separates it into two.

transforms: (convert_stream_to_snax_stream) split up layout resolution pass

---

benchmarks/dense_matmul/Makefile
compiler/tools/snax_opt_main.py
compiler/transforms/convert_dart_to_snax_stream.py
compiler/transforms/dart/dart_layout_resolution.py
compiler/transforms/dart/dart_scheduler.py
kernels/gemm/Snakefile
kernels/rescale/Snakefile
kernels/streamer_alu/Snakefile
kernels/streamer_matmul/Snakefile
tests/filecheck/transforms/convert-dart-to-snax-stream.mlir

This splits the three patterns into separat transformations. This will allow me to:
- Test the intermediate stages more properly
- Put other transforms in between that act on the intermediate representations

split up dart transformations

---

pixi.lock
util/snake/configs.py
util/snake/flags.py
util/snake/paths.py

I'm trying to get rid of some pyright errors, but some are quite difficult to solve.
Things I learned:
* Pandas has a pandas-stubs library that needs to be installed to be able to even do type checking.
* Pandas-stubs does not fully conform to pyright's strict mode (this can be overridden with a specific pyrightconfig.json file though.

Solve pyright errors for util/snake

---

compiler/ir/dart/access_pattern.py
tests/ir/dart/test_access_pattern.py

This is meant to replace `disable_dims`, as it is much more intuitive and easier to use. The algorithms are still processing this change, so `disable_dims` is just deprecated for now.

add access pattern inner_dims method

---

compiler/ir/dart/access_pattern.py
tests/ir/dart/test_access_pattern.py

stacked on #349 
with this PR, when doing a template check with a template and a schedule, previously they are forced to the same number of dims. This PR checks if the schedule has larger dimensionality than the template, and reduces it to the number of dims of the template in this case.

template matching: only look at the inner dims of the schedule

---

tests/filecheck/transforms/dart/dart-scheduler.mlir

stacked on #350 
The scheduler itself is tested quite rigorously in pytests, this filecheck just makes sure that the pass applying the scheduler works correctly, which is why I feel a single test is enough

add dart-scheduler simple filecheck

---

compiler/ir/dart/access_pattern.py
tests/ir/dart/test_access_pattern.py

this removes the `disable_dims` method as replaced by `inner_dims` in #349, made possible by the changes in #350

delete access_pattern disable_dims

---

compiler/ir/dart/scheduler.py
tests/ir/dart/test_scheduler.py

stacked on #350 
This one adds the capability to the scheduler to add extra checks/ constraints to filter out unwanted schedules, and adds a check to only accept pure output stationary (= never send partial results back to memory) schedules.
This is a useful  check for for example accelerators which do not have the capability to preload partial results. In our case the codegen further down the pipeline is not yet capable of non-output stationary schedules.
Currently, this constraint is embedded in accelerator templates in a hacky way. This way of handling things makes it more explicit and controllable.

add optional output stationary check

---

compiler/transforms/dispatch_regions.py
tests/filecheck/transforms/dispatch_regions.mlir

I encountered some bugs with the following two tests relating regions, where a dispatchable op just before another op with a region is moved to that region, instead of before the op
(I also converted the filecheck to not use generic format to make it much more readable in general)
Input:
```
func.func public @func() {
%0 = memref.alloc() {alignment = 64 : i64} : memref<16x16xi8>
%1 = memref.alloc() {alignment = 64 : i64} : memref<16x16xi8>
"memref.copy"(%0, %1) : (memref<16x16xi8>, memref<16x16xi8>) -> ()
"test.op"() ({
"test.op"() : () -> ()
"test.termop"() : () -> ()
}): () -> () 
func.return
}
```
Output (before this PR)
```
builtin.module {
func.func public @func() {
%0 = func.call @snax_cluster_core_idx() {pin_to_constants = [0 : i32, 1 : i32]} : () -> i32
%1 = arith.constant 1 : i32 …
```

fix some dispatch_regions bugs

---

benchmarks/dense_matmul/Makefile
benchmarks/dense_matmul/genbenchmark.py
compiler/transforms/set_memory_layout.py
tests/filecheck/transforms/set-memory-layout.mlir

use auto-generated cyclic layouts

---

pixi.lock
pyproject.toml

the cache keeps being annoying (?)
xdsl has already moved on to a new commit, so the next package on conda can be clean again

use .c version of mlir conda package

---

pixi.lock
pyproject.toml
snaxc/dialects/kernel.py
tests/filecheck/transforms/convert-linalg-to-kernel.mlir

a mac region includes extsi if output type != input type

convert-linalg-to-kernel: add optional extsi to mac kernel

---

snaxc/ir/dart/access_pattern.py
tests/ir/dart/test_access_pattern.py
tests/ir/dart/test_scheduler.py

This replaces the naive check if a template matches a schedule with a bit more of a robust one.
While this one is pretty slow, it seems to work very reliably.
If we were to replace this with a better check, at least this one can serve as a benchmark for matching schedules.
This is mainly necessary for convs where the index space is 4D (NCHW) but the accelerator only considers 2 dimensional inputs and outputs

singular value template matching

---

kernels/gemm/main.c
kernels/streamer_matmul/main.c
runtime/include/snax_rt.h
snaxc/transforms/convert_dart_to_snax_stream.py
tests/filecheck/transforms/convert-dart-to-snax-stream.mlir

this removes the hack to load in zeros via the d32 port to disable the bias addition. the hack is causing some issues.
if we want to compute a matmul without starting from the initial values already present in the output memref, we should provide a more explicit solution for this case
in the case of the current kernels, they are functional as tcdm is initialized to zeros anyway

remove zero bias hack

---

snaxc/transforms/set_memory_layout.py

otherwise the layout transformations get a bit messed up.
this is probably something we want to support in the future, but don't right now.

set-memory-layout: only tile if it is nicely divisible

---

.github/workflows/build-run-kernel-snake.yml
kernels/conv/Snakefile
kernels/conv/conv.py
kernels/conv/main.c

this adds a kernel to execute convolutions on the gemmx.
with the convspec, different variations of a convolution can be generated, golden results are computed using tensorflow, and the result is given as a `linalg.conv2d_nchw_fchw`.
In ci, the default is a `16x16x16` output with a kernel size of `16x16x3x3`.
I will expand this in future PRs

add conv kernel

---

snaxc/ir/dart/scheduler.py
snaxc/transforms/dart/dart_scheduler.py
tests/ir/dart/test_scheduler.py

for now, the scheduler just returns the first valid schedule.
while the selection of schedule should be a bit smarter, this allows for a selection of a specific index in the list of valid indeces as shortcut or to explore multiple of them

transform: (dart-scheduler) enable schedule idx in scheduler

---

snaxc/transforms/set_memory_layout.py
tests/filecheck/transforms/set-memory-layout.mlir

when choosing an automatic layout, the selection to tile or not to tile is a bit more complex.
As the streamers can only have affine access patterns, the resulting patterns after tiling must remain affine, which is what this one checks.

transform: (set-memory-layout) only tile layout if all patterns remain affine

---

snaxc/ir/dart/access_pattern.py
snaxc/transforms/dart/dart_scheduler.py
snaxc/transforms/set_memory_layout.py
tests/ir/dart/test_access_pattern.py

canonicalize operation schedules before applying the scheduler to avoid duplicate results
For example a for loop with bound 1 is useless, but rotating this one around results in several valid schedules that are actually equal. Therefore there is a canonicalization step before applying the scheduler

add dart schedule canonicalization

---

snaxc/transforms/snax_copy_to_dma.py
tests/filecheck/transforms/copy-to-dma-ignore-transform.mlir

sometimes you just want to ignore all transformations made by the dma because it makes everything very slow, this gives you the option to replace it by a regular 1D transfer.
The data will be wrong, but it can be helpful during debugging

transforms: (snax-copy-to-dma) add ignore transform option

---

.github/workflows/build-run-kernel-snake.yml
kernels/mlp/Snakefile
kernels/mlp/main.c
kernels/mlp/mlp.py

In this PR, let's try out an MLP where you can vary the input size, hidden layers, and output sizes. 
Things you will find:
⭐  A *golden* function to produce MLP outputs
⭐  The MLIR programming function
⭐ The other things required to run on a certain SNAX cluster architecture
🌋 : I purposely separated this so I can modularize and make comparisons. I know in other examples we can combine them into one, but I did this for my *learning* purposes.
⚠️ Right now this is not "perfect" as it complains about the sign extension due to the `i32` output of the matmul operation. We need a scaling capability.
For now, I assumed that the outputs are indeed 32 bit but setting the types to 8bits complains more. So I get this error after running `snax-opt`:
```bash
tensor<1x3xi32>
%21 = "tensor.empty"() : …
```

Adding an MLP program

---

snaxc/dialects/__init__.py
snaxc/dialects/pipeline.py
tests/filecheck/dialects/pipeline/ops.mlir

this PR adds an initial version of the pipeline dialect
this will be used in transformations to construct pipelines from for loop blocks, that can then later be unrolled to achieve double buffering and multi-core pipelined scenarios

add pipeline dialect

---

snaxc/dialects/pipeline.py
snaxc/transforms/__init__.py
snaxc/transforms/pipeline/construct_pipeline.py
tests/filecheck/transforms/pipeline/construct-pipeline.mlir

This pattern will construct a pipeline operation from a for loop.
It tries to detect a structure in the following manner:
```
for:
(index_ops):
(stage_1):
(cluster_sync)
(stage_2)
(cluster_sync)
...
```
This structure is then converted to a pipeline op, such that it can
be urnolled in further transformations to achieve double buffering
and pipelined execution of asynchronous multi-core accelerators.

transforms: add construct-pipeline pass

---

kernels/streamer_matmul/Snakefile
kernels/streamer_matmul/main_i8.c
kernels/streamer_matmul/matmul_i8_out.py

this adds a unit test for deploying macs (i8, i8 -> i8) to the gemmx. if no specific rescaling is specified,
a default right shift of >> 9 is applied.
Mostly useful for testing and quick benchmarking purposes.
Support for this was added in #404 and #406

add gemmx streamer matmul test for default i8 output

---

.github/workflows/build-run-mlperf-tiny.yml
pixi.lock
pyproject.toml
runtime/Makefile.rules
snaxc/accelerators/acc_context.py
snaxc/dialects/accfg.py
snaxc/dialects/snax.py
snaxc/transforms/accfg_dedup.py
snaxc/transforms/clear_memory_space.py
snaxc/transforms/convert_linalg_to_accfg.py
snaxc/transforms/dart/dart_fuse_operations.py
snaxc/transforms/frontend/preprocess_mlir.py
snaxc/transforms/frontend/preprocess_mlperf_tiny.py
snaxc/transforms/memref_to_snax.py
snaxc/transforms/set_memory_space.py
tests/dialects/test_snax.py
tests/filecheck/transforms/insert-sync-barrier.mlir
tests/filecheck/transforms/realize-memref-casts.mlir

this disables the mlperf tiny workflow because tensorflow is not updating fast enough, see #419

bump xdsl and llvm

---

tests/filecheck/transforms/realize-memref-casts.mlir

filecheck: (realize-memref-casts) disable generic print in filecheck

---

snaxc/transforms/realize_memref_casts.py

to enable more constant transformations with code reuse (not only arith.constant, but also memref.global)

transforms: (realize-memref-casts) refactor op rewriting 

---

snaxc/transforms/set_memory_space.py
tests/filecheck/transforms/set-memory-space.mlir

an else case was missing in the transform logic to handle this case

transforms: (set-memory-space) handle func.return for different memory spaces

---

kernels/alloc/Snakefile
snaxc/accelerators/acc_context.py
snaxc/tools/snax_opt_main.py
snaxc/transforms/snax_allocate.py
util/snake/configs.py

For this, the accelerator context changes somewhat so that not all memories are registered by default.
For snax-opt we explicitly then register all of them such that testing passes remain functional.

 kernels: (alloc) use snax_alu specific config for use with snaxc tool 

---

snaxc/transforms/__init__.py
snaxc/transforms/frontend/frontend_transform.py

to replace the calling of transform interpreter now present in the snakefiles
this doesn't allow for the use of binding trailing args, so transform scripts should use match operations instead of block arguments

transforms: (frontend-transform) add frontend transform pass

---

snaxc/dialects/tsl.py
tests/filecheck/transforms/copy-to-dma-ignore-transform.mlir
tests/filecheck/transforms/copy_to_dma.mlir
tests/filecheck/transforms/memref_to_snax.mlir

this fixes a bug where the TSL code created operations that weren't inserted into the IR, which causes some tricky issues later

tsl: fix bug when not inserting created ops

---

snaxc/transforms/dispatch_regions.py

creating ops that are not used can cause issues with xdsl

transforms: (dispatch-regions) erase ops that are not inserted

---

kernels/streamer_matmul/Snakefile
kernels/streamer_matmul/tiled_quantized_matmul.py
snaxc/transforms/frontend/frontend_transform.py

such that the pass can be applied to any ir (even those without transform script) without erroring out
this gets rid of the seperate rule in the streamer matmul kernel

transforms: (frontend-transform) only apply mlir pass if module contains transform script

---

kernels/rescale/Snakefile
kernels/rescale/main.c
kernels/rescale/rescale.mlir

because allocation now happens in snax-mlir, the zero row hack to be able to run this test is now ported to mlir instead of the main.c

kernels: (rescale) use snaxc tool

---

snaxc/tools/snaxc_main.py
snaxc/transforms/alloc_to_global.py
tests/filecheck/transforms/alloc-to-global.mlir

Allocs that are returned in a function, must be initialized as a global such that they can be read from the function caller in any scenario. Intermediate allocs can remain as we can later determine where they ought to be allocated.
Additionally, memref.allocs with a specified memory space are also ignored.
This allows us to move up the alloc-to-global pass way back up, where it is supposed to be.

transforms: (alloc-to-global) only globalize allocs used in terminator ops

---

snaxc/transforms/pipeline/unroll_pipeline.py
tests/filecheck/transforms/pipeline/unroll-pipeline.mlir

the final iteration of the pipeline was done with index = ub, but the last one should be done with ub - 1 instead. This PR fixes this bug.

transforms: (unroll-pipeline) postamble ends with ub - 1

---

snaxc/ir/dart/access_pattern.py
tests/ir/dart/test_scheduler.py

This adds broadcasting support to the scheduler for a relatively simple case:
when the dimensions of the resulting space of the schedule is less than the template, only the inner dimension is considered, in the assumption that other dimensions can be broadcasted to.

add broadcasting support to scheduler

---

snaxc/dialects/snax_stream.py
snaxc/transforms/convert_dart_to_snax_stream.py

There is an exception to the non-contiguity check if broadcasting is used, as only the first streamer is active and then contiguity is no longer a restriction.

transforms: (convert-dart-to-snax-stream) add support for broadcasting

---

snaxc/transforms/set_memory_layout.py
tests/filecheck/transforms/set-memory-layout.mlir

just the start of a better system, set layouts such that access
granularity of the streamers towards the tcdm is compliant with
connectivity

transforms: (set-memory-layout) add access granularity constraints

---

snaxc/transforms/dart/dart_bufferize.py
snaxc/transforms/snax_bufferize.py

they are not supported, if you want some kind of initialization, this should happen with an explicit add that can be fused. These patterns to do this automatically will be added in the near future.
Some kernels trigger this warning, and this may be helpful to debug future undefined behaviour.

transforms: (dart-bufferize) add warning for non-empty inits

---

snaxc/transforms/dart/convert_linalg_to_dart.py
tests/filecheck/transforms/convert-linalg-to-dart.mlir

when converting a linalg that starts from certain initial values, explicitly transform that into an add operation for a simple case of an arith.constant

transforms: (convert-linalg-to-dart) turn arith.constant init into explicit add

---

kernels/gemm/gemm_broadcast.py
snaxc/accelerators/gemmini.py
snaxc/transforms/frontend/preprocess_mlir.py

the linalg-fuse-elementwise-ops messes up further lowerings, so we should not depend on it. Therefore, the broadcast add is modified to be generated with a linalg.generic directly, rather than a broadcast + add we then fuse together.

kernels: (gemm) modify gemm_broadcast to avoid linalg fuse pass

---

kernels/mlperf_tiny/Snakefile
kernels/mlperf_tiny/gendata.py
kernels/mlperf_tiny/main.c
util/gendata.py

Now, sample data is downloaded along with the mlir network. Sample data is broadcasted by the gendata.py script for batched execution, and turned into a proper data.h.
The main file calculates the mean square error between sample data and simulator output.
If the error is > 5, we throw an error.
Currently, the error is all 1 (golden[i] = output[i] + 1). I have no idea why

networks: (mlperftiny-ad01) add output checking to network

---

snaxc/transforms/convert_tosa_to_kernel.py

transforms: (convert-tosa-to-kernel) allow for 4D tensors

---

snaxc/transforms/dart/dart_fuse_operations.py

the previous check only works on 2d matrices

transforms: (dart-fuse-operations) fix broadcasting check

---

snaxc/transforms/convert_kernel_to_linalg.py

to be used when deploying neural networks, when dispatching a rescale op has failed, such that we still generate valid linalg that can be ran on the risc-v cores in the cluster

transforms: (convert-kernel-to-linalg) add simple rescale lowering

---

pixi.lock
pyproject.toml

this newer version of minimalloc has the C library built on a system with an older version of glibc, such that it would work on the esat servers

update minimalloc git commit

---

snaxc/transforms/alloc_to_global.py
tests/filecheck/transforms/alloc-to-global.mlir

Uninitialized variables are currently very slow, so this avoids them until they are fast again.
See kuleuven-micas/snax_cluster#532 for more details

transforms: (alloc-to-global) initialize to default value to avoid .bss

---

snaxc/accelerators/accelerator.py
snaxc/accelerators/rocc.py
snaxc/accelerators/snax.py
snaxc/accelerators/snax_gemmx.py

there are some example cases, for example the gemmx quantization params that require specific accelerator information

accfg: lower_acc_launch is not always static
