- container/Dockerfile
This pull request adds the stardew installation to the Docker container.
> Add stardew installation to docker container

- kernels/simple_mult/main.c
- runtime/Makefile.rules
Adds calls to HWPE accelerator with the refactored library
> Add calls to hwpe simple mult accelerator

- README.md
> update readme with new flow

- kernels/alloc/Makefile
- kernels/simple_copy/Makefile
- kernels/simple_mult/Makefile
- runtime/Makefile.rules
- runtime/snax-mac.rules
Stacked on top of #36
To add more RTLs later.
> Refactor Makefile rules for multiple RTLs

- kernels/simple_mult/gendata.py
- kernels/simple_mult/linalg.mlir
- kernels/simple_mult/main.c
> Add actual check on golden output

- .github/workflows/build-run-kernel.yml
- .github/workflows/lit-tests.yml
- .github/workflows/python-tests.yml
> fix actions

- .github/workflows/lit-tests.yml
- .github/workflows/python-tests.yml
Also run actions on pull requests that do not go to the main branch. I want this for #55 for example, and there is no reason to not do this.
> Alter actions pull request trigger

- compiler/tools/snax_opt_main.py
- requirements.txt
Pass registration API has changed since https://github.com/xdslproject/xdsl/pull/1917
> Adapt pass registration API to upstream

- compiler/ir/tsl/README.md
small error such that image is not shown
> Fix TSL Docs

- compiler/dialects/snax.py
- compiler/util/memref_descriptor.py
- tests/dialects/test_snax.py
- tests/filecheck/dialects/snax/snax_invalid.mlir
- tests/filecheck/dialects/snax/snax_ops.mlir
- tests/filecheck/lit.cfg
- tests/util/test_memref_descriptor.py
This PR adds the `snax.alloc` operation
This also includes the util class for the `LLVMMemrefDescriptor`
> add snax.alloc op

- compiler/ir/tsl/tiled_strided_layout.py
- compiler/transforms/set_memory_layout.py
- compiler/transforms/snax_copy_to_dma.py
- kernels/simple_matmul/Makefile
- kernels/simple_matmul/cpu.mlir
- kernels/simple_matmul/gendata.py
- kernels/simple_matmul/main.c
- kernels/simple_matmul/matmul.mlir
- runtime/Makefile.rules
- runtime/include/snax_rt.h
- tests/filecheck/transforms/set-memory-layout.mlir
lets fucking goo 🤘 
This successfully replaces the matmul kernel with a full end-to-end flow, combining the work of a lot of previous PRs
It also uses the actual GEMM hardware instead of the cpu golden model!
I think we can say this resolves #23
> end-to-end matrix multiplication

- .pre-commit-config.yaml
> Happy 100th PR!

- .github/workflows/pact-tests.yml
- compiler/tools/snax_opt_main.py
- compiler/transforms/set_memory_layout.py
- pact/experiments/layout/Makefile
- pact/experiments/layout/create_summary.py
- pact/experiments/layout/generate_tests.py
- pact/experiments/layout/main_template_base.c_template
- pact/experiments/layout/main_template_cpu.c_template
- pact/experiments/layout/main_template_fifo.c_template
- pact/experiments/layout/makefile_template
- pact/experiments/layout/mlir_template.mlir
- pact/experiments/layout/parse_logs.py
- requirements.txt
- runtime/snax-streamer-gemm-fifo-0.rules
- runtime/snax-streamer-gemm-fifo-1-slow.rules
- runtime/snax-streamer-gemm-fifo-1.rules
- runtime/snax-streamer-gemm-fifo-2.rules
- runtime/snax-streamer-gemm-fifo-3.rules
- runtime/snax-streamer-gemm-fifo-4.rules
> layout experiments: add tests

- .gitignore
I'm just copying some stuff from xDSL so that I have less pain with git :smile:
> Add stuff to gitignore

- compiler/inference/trace_acc_state.py
- compiler/tools/snax_opt_main.py
- compiler/transforms/convert_linalg_to_acc.py
- tests/filecheck/transforms/accfg-trace-states.mlir
> accfg: Add scf for loop state tracing

- compiler/accelerators/registry.py
- compiler/accelerators/snax.py
- compiler/accelerators/snax_gemm.py
- compiler/accelerators/snax_hwpe_mult.py
- compiler/transforms/dispatch_kernels.py
- compiler/transforms/set_memory_layout.py
- kernels/simple_matmul/Makefile
- kernels/simple_matmul/main.c
- tests/filecheck/transforms/dispatch_kernels.mlir
- tests/filecheck/transforms/realize-memref-casts.mlir
- tests/filecheck/transforms/set-memory-layout.mlir
Initial work on non-streamer gemm accelerator through accfg dialect
> accfg: Add SNAX gemm accelerator

- compiler/dialects/tsl.py
- compiler/tools/snax_opt_main.py
- compiler/transforms/convert_accfg_to_csr.py
- container/Dockerfile
- requirements.txt
- tests/filecheck/transforms/acc-dedup.mlir
- tests/filecheck/transforms/accfg-trace-states.mlir
- tests/filecheck/transforms/convert-acc-to-csr.mlir
- tests/filecheck/transforms/convert-linalg-to-acc.mlir
Tiny PR to update to latest xDSL
> upgrade to latest xDSL (stacked 1/3)

- compiler/dialects/snax.py
- compiler/transforms/memref_to_snax.py
- compiler/transforms/set_memory_space.py
- compiler/transforms/snax_to_func.py
- compiler/util/snax_memory.py
- tests/dialects/test_snax.py
- tests/filecheck/dialects/snax/snax_ops.mlir
- tests/filecheck/dialects/tsl/tsl.mlir
- tests/filecheck/transforms/copy_to_dma.mlir
- tests/filecheck/transforms/insert-sync-barrier.mlir
- tests/filecheck/transforms/memref_to_snax.mlir
- tests/filecheck/transforms/realize-memref-casts.mlir
- tests/filecheck/transforms/set-memory-space.mlir
- tests/filecheck/transforms/snax_to_func.mlir
This PR changes the default usage of integer memory space attributes to string memory attributes
> Use string memory spaces

- compiler/ir/tsl/tiled_strided_layout.py
works on my machine
@JosseVanDelm
> error on dynamic lcb

- compiler/transforms/snax_copy_to_dma.py
> add offset when constructing tsl from strides

- compiler/transforms/convert_accfg_to_csr.py
Notices a the new rewriting behaviour to fail when erasing state variables in loops, so now I made our rewrite tell the rewriter that we are in *expert mode*.
> Where we are going we don't need safety

- .github/workflows/build-run-kernel.yml
- .github/workflows/build-run-mlperf-tiny.yml
- .github/workflows/lit-tests.yml
- .github/workflows/python-tests.yml
- kernels/streamer_alu/main.c
to get the hardware fix of kuleuven-micas/snax_cluster#163
> bump snax to v0.1.3

- .github/workflows/build-run-kernel.yml
Just trying something out that ChatGPT suggested
> Add github actions matrix

- requirements.txt
> switch to filecheck-ng

- compiler/dialects/tsl.py
- compiler/transforms/dispatch_regions.py
- runtime/Makefile.rules
- tests/filecheck/transforms/dispatch_regions.mlir
Fix bug where dispatch_regions would add if-statement inside the if-statements own region, thus creating a loop. This is solved using region_first option. a test was added
> fix dispatch regions

- requirements.txt
new xDSL version to support Transform dialect
> bump xDSL (#199)

- compiler/transforms/accfg_dedup.py
Merge ops to last op and not to previous op. Solves #202
> Fix error in MergeSetupOps()

- compiler/transforms/dispatch_regions.py
- kernels/tiled_add/tiled.preprocfinal.mlir
- kernels/tiled_add/tiled_pipelined.preprocfinal.mlir
- kernels/tiled_add/untiled.mlir
- runtime/include/snax_rt.h
- tests/filecheck/transforms/dispatch_regions.mlir
This makes it easier to use the function constant pinning pass of Anton
> Switch region dispatch to use core index directly

- requirements.txt
- tests/filecheck/transforms/copy_to_dma.mlir
I need to have this for https://github.com/xdslproject/xdsl/pull/3127
> Bump xdsl version

- compiler/inference/scoped_setups.py
- compiler/transforms/accfg_config_overlap.py
Fix in scoped_setups, originally in #224 , but now cherry-picked from 9060797ccb8ef1ebe67078382ba1c60a5f5d569c
> Add fix in scoped_setups

- compiler/accelerators/snax.py
- compiler/accelerators/snax_gemmx.py
- compiler/accelerators/streamers/streamers.py
- compiler/dialects/snax.py
- tests/filecheck/dialects/snax/snax_ops.mlir
new features include:
- sometimes the bounds are programmed separately, sometimes not 😫 (this should be resolved after the streamer merge but I want to first support neural networks before we use the new streamers)
- readerwriter is now also a possiblity!
- readertranspose is now also a possibility!
> streamer_config: update to the latest streamer features

- .github/workflows/run-benchmarks.yml
had to bump to v0.2.1 also here
> fix benchmarks ci

- compiler/accelerators/snax.py
- compiler/accelerators/snax_gemmx.py
- compiler/accelerators/streamers/streamers.py
- compiler/dialects/snax.py
- tests/filecheck/dialects/snax/snax_ops.mlir
a better way to specify the custom options of streamers, every streamer now has a set of "options" to determine its capabilities
> introduce streamer opts

- .github/workflows/build-run-kernel.yml
- .github/workflows/build-run-mlperf-tiny.yml
- .github/workflows/lit-tests.yml
- .github/workflows/python-tests.yml
- .github/workflows/run-benchmarks.yml
- compiler/accelerators/snax.py
- compiler/accelerators/snax_gemmx.py
This mostly includes the channelwise quantization features of the simd in gemmx!
The lowerings still assume one single quantization factor, thus the same one is programmed to all separate channels
> bump snax to v0.2.2

- runtime/Makefile.rules
- util/snax_benchmark.py
change to accomodate for: https://github.com/KULeuven-MICAS/snax_cluster/pull/351
> fix bug: traces have new names

- .gitattributes
to set up a benchmarking site!
> setup git lfs

- .github/workflows/gh-pages.yml
thank you dawidd6 for making this surprisingly easy
> use artifacts in gh-pages workflow

- compiler/dialects/stream.py
- compiler/tools/snax_opt_main.py
- compiler/transforms/snax_bufferize.py
- compiler/transforms/stream_bufferize.py
- tests/filecheck/transforms/stream-bufferize.mlir
This pass partially bufferizes streaming regions, such that --one-shot-bufferize of mlir works!
> add stream-bufferize pass

- compiler/accelerators/snax.py
- compiler/accelerators/snax_alu.py
- compiler/accelerators/snax_gemm.py
- compiler/accelerators/snax_gemmx.py
- compiler/transforms/convert_stream_to_snax_stream.py
- compiler/transforms/schedule_memref_linalg.py
This is much cleaner and solves a couple of fixme's
> move template definitions to the accelerators

- compiler/transforms/realize_memref_casts.py
only change needed is to add support for detecting inputs/outputs of streaming regions
> transforms: (realize-memref-casts) make compatible with streaming regions

- compiler/transforms/set_memory_layout.py
- tests/filecheck/transforms/set-memory-layout.mlir
the pass was only compatible with linalg.generics, this change updates it to also be compatible with streaming regions
> transforms: (set-memory-layout) make compatible with streaming region

- compiler/transforms/set_memory_space.py
- tests/filecheck/transforms/set-memory-space.mlir
same as linalg.generics, force all memrefs to L1 for these operations
> transforms: (set-memory-space) add support for streaming regions

- compiler/ir/stream/access_pattern.py
- compiler/ir/stream/scheduler.py
- compiler/transforms/convert_stream_to_snax_stream.py
- compiler/util/canonicalize_affine.py
- tests/dialects/test_tsl.py
- tests/ir/stream/test_access_pattern.py
- tests/ir/stream/test_scheduler.py
- tests/util/test_canonicalize_affine.py
This adds some tests to the streamer scheduler for the currently supported cases, and includes little bugfixes for some cases I thought would be currently supported but apparently were not.
> add scheduler tests

- compiler/transforms/snax_bufferize.py
- kernels/streamer_matmul/Makefile
- kernels/streamer_matmul/tiled_quantized_matmul.py
- runtime/Makefile.rules
> add tiled quantized matmul kernel

- .gitattributes
- .gitignore
- pixi.lock
- pyproject.toml
Initializes the pixi properties for the python packages.
This currently restricts the python version to `3.10.*`, something that can be updated further down the line
> add pixi python initialization

- pixi.lock
- pyproject.toml
this adds dependencies to the (approximately) same commit as xdsl is based on.
Locally with very little changes (paths to binaries and so on), and the /opt folder from the docker container copied locally,
this compiled and simulated a kernel successfully!
> pixi: add mlir, clang, lld

- pixi.lock
- pyproject.toml
This is a global update of python, numpy and to add snakemake
> Update python and numpy, add snakemake-minimal

- benchmarks/dense_matmul/gendata.py
- benchmarks/tiled_matmul/gendata.py
I messed up some of the benchmarks in #318
> Fix gendata.py for benchmarks

- .github/workflows/run-benchmarks.yml
- runtime/Makefile.rules
These are not yet converted to snake?
> fix benchmark after llvm12 deletion

- pixi.lock
- pyproject.toml
Bumps to a new version that should not have glibc errors and that should work allow us to parallelize binary runs :)
> Bump snax-cluster version

- compiler/ir/dart/scheduler.py
- tests/ir/dart/test_scheduler.py
stacked on #351 -> #349 
This PR implements a nicer scheduler using a backtracking algorithm to generate valid schedules on the operation.
> add backtracking scheduler

- compiler/tools/snax_opt_main.py
- compiler/transforms/__init__.py
Similar to #357 , but now for passes/transforms
> Add lazy pass loading

- util/snake/configs.py
- util/snake/flags.py
After this pull request you can set the includes of the runtime paths of this repository, if you are using it from another repository
> Parameterize-snax-mlir-path

- runtime/include/memref.h
>  add some more memref types 

- pixi.lock
- pyproject.toml
We use it for quite some things now
> add numpy dependency explicitly

- .github/workflows/run-benchmarks.yml
- runtime/Makefile.rules
Looks like #366 broke some stuff. Oops!
> Fix benchmarks

- util/tracing/trace_to_perfetto.py
https://github.com/KULeuven-MICAS/snax-mlir/actions/runs/13564819423/job/37915464063
> Fix benchmark registry reference

- snaxc/ir/dart/access_pattern.py
small quality of life improvement to help with debugging flows
> add pretty printing to templates

- snaxc/accelerators/snax_gemmx.py
the current method to determine the k,n and m values to program to the accelerator only work for 3 dimensional stride patterns, which is no longer the case for convolutions
> better knm generation for gemmx

- snaxc/accelerators/snax_gemmx.py
- snaxc/transforms/convert_dart_to_snax_stream.py
using the i8 output without explicit rescaling will just set the shift to 9 (/512), for some testing purposes
> add i8 output support for mac kernels on gemmx

- snaxc/dialects/pipeline.py
> add pipeline op helpers

- snaxc/transforms/__init__.py
- snaxc/transforms/pipeline/unroll_pipeline.py
- tests/filecheck/transforms/pipeline/unroll-pipeline.mlir
> transforms: add unroll-pipeline transform

- .github/workflows/build-run-mlperf-tiny.yml
the mlir tensorflow mess is solved in https://github.com/kuleuven-micas/mlir-networks
> re-enable mlperf tiny workflow

- snaxc/transforms/memref_to_snax.py
- snaxc/transforms/set_memory_space.py
- snaxc/transforms/snax_to_func.py
- snaxc/util/snax_memory.py
to enable static memory allocation schemes
> expand memory space information

- benchmarks/dense_matmul/Makefile
- benchmarks/tiled_matmul/Makefile
- kernels/alloc/Snakefile
- kernels/conv/Snakefile
- kernels/gemm/Snakefile
- kernels/mlp/Snakefile
- kernels/rescale/Snakefile
- kernels/simple_copy/Snakefile
- kernels/streamer_alu/Snakefile
- kernels/streamer_matmul/Snakefile
- kernels/tiled_add/Snakefile
- kernels/transform_copy/Snakefile
- runtime/Makefile.rules
- snaxc/transforms/__init__.py
- snaxc/transforms/snax_allocate.py
- snaxc/transforms/snax_to_func.py
- tests/filecheck/transforms/snax-allocate.mlir
- tests/filecheck/transforms/snax_to_func.mlir
- util/snake/configs.py
to prepare expanding to other allocation strategies
> transforms: move allocation out of snax-to-func

- snaxc/transforms/snax_allocate.py
for code reuse in new allocation strategies
> transforms: snax-allocate refactor llvm memref struct generation

- snaxc/transforms/snax_allocate.py
- snaxc/util/snax_memory.py
- tests/filecheck/transforms/snax-allocate-static.mlir
this adds a simple static allocator with incrementing memory addresses for every new alloc
> transforms: snax-allocate add static allocator

- pixi.lock
- pyproject.toml
- snaxc/transforms/snax_allocate.py
- tests/filecheck/transforms/snax-allocate-minimalloc.mlir
This adds an static allocation algorithm based on the minimalloc algorithm
> transforms: snax-alloc add minimalloc allocation scheme

- util/snake/paths.py
- util/snake/snax.smk
with a small gotcha: defaulting to gemmx accelerator for now
> snake: add trace_to_perfetto rule

- snaxc/transforms/clear_memory_space.py
when clearing the layout for subview ops, we must reset a layout with a strided attribute for mlir to be okay with this
> transforms: (clear-memory-space) add support for subview ops

- snaxc/transforms/realize_memref_casts.py
- tests/filecheck/transforms/realize-memref-casts.mlir
to enable efficient static layout transformations on tiled programs
> transforms: (realize-memref-casts) apply layout transformation on subview source

- snaxc/transforms/pipeline/construct_pipeline.py
the variable i was being overwritten here, causing some issues
> transforms: (construct-pipeline) fix reuse i bug

- snaxc/transforms/dart/convert_linalg_to_dart.py
- tests/filecheck/transforms/convert-linalg-to-dart.mlir
similar to #500, for linalg.yield inits, such that broadcasting patterns can be supported
> transforms: (convert-linalg-do-dart) turn linalg.yield init into explicit adds

- snaxc/dialects/kernel.py
- snaxc/transforms/convert_tosa_to_kernel.py
also changes the attributes to properties
> dialects: (kernel) add init for RescaleOp

- snaxc/transforms/convert_dart_to_snax_stream.py
again, this should be taken out of this pass as soon as possible!
I believe all of this logic should be caputered by the accelerator implementation itself, rather than this specific lowering.
> transforms: (convert-dart-to-snax-stream) add support for gemm + recale for gemmx

- kernels/conv/Snakefile
- kernels/conv/config.yaml
- kernels/conv/conv.py
this then also adds one test with an underutilized array
> kernels: (conv) allow for multiple convspecs in snakefile

- pixi.lock
- pyproject.toml
- snaxc/accelerators/configurable_accelerator.py
- snaxc/accelerators/snax_alu.py
- snaxc/accelerators/snax_gemmx.py
- snaxc/tools/config_parser.py
- snaxc/tools/configs.py
- snaxc/util/snax_memory.py
- util/ssot/snax_alu.yaml
- util/ssot/snax_gemmx.yaml
This creates a dataclass based structure for parsing the target config files, to build up the accelerator context in a more structured way.
> implement config parser based on dacite

- kernels/rescale/rescale_golden/rescale_combined.mlir
- snaxc/transforms/__init__.py
- snaxc/transforms/combine_rescale.py
- tests/filecheck/transforms/combine-rescale.mlir
- tests/filecheck/transforms/tosa-combine-rescale.mlir
This PR adds functionality and tests for the CombineRescale pass which takes 2 subsequent rescales and transforms them into a single operation.
> transforms: (combine rescale) Add combine Rescale Pass

- util/snake/configs.py
> snake: remove mlperf_tiny_config
